export const MODULES = [
  {
    key: 'dashboard',
    title: 'Panel principal',
    subtitle: 'Estado general del sistema Tauros',
    path: '/dashboard',
    endpoint: '',
    fields: [],
    canCreate: false,
    canDelete: false,
  },
  {
    key: 'usuario',
    title: 'Usuarios',
    subtitle: 'Gestion de usuarios registrados',
    path: '/usuarios',
    endpoint: '/usuario',
    idField: 'userId',
    fields: ['nombre', 'apellido', 'correo', 'cedula', 'rol', 'isActive'],
    formFields: ['cedula', 'nombre', 'apellido', 'fechaNacimiento', 'correo', 'password', 'telefono', 'rol'],
    canCreate: true,
    canDelete: true,
  },
  {
    key: 'composicion-corporal',
    title: 'Composicion corporal',
    subtitle: 'Mediciones y progreso de usuarios',
    path: '/composicion-corporal',
    endpoint: '/composicion-corporal',
    idField: 'composicionCorporalId',
    fields: ['usuario.nombreCompleto', 'peso', 'talla', 'grasaCorporal', 'edadCorporal', 'grasaVisceral', 'masaMuscularKg', 'masaMuscularPorcentaje', 'masaMuscularTipo', 'fechaRegistro'],
    formFields: ['peso', 'talla', 'grasaCorporal', 'edadCorporal', 'grasaVisceral', 'masaMuscularKg', 'masaMuscularPorcentaje', 'masaMuscularTipo', 'usuarioId'],
    numberFields: ['peso', 'talla', 'grasaCorporal', 'edadCorporal', 'grasaVisceral', 'masaMuscularKg', 'masaMuscularPorcentaje'],
    canCreate: true,
    canDelete: true,
  },
  {
    key: 'ejercicio',
    title: 'Ejercicios',
    subtitle: 'Gestion de ejercicios y activacion muscular',
    path: '/ejercicios',
    endpoint: '/ejercicio',
    idField: 'ejercicioId',
    fields: ['ejercicioId', 'nombre', 'categoria.nombre', 'tipo.nombre', 'maquina.nombre', 'linkVideo', 'linkAM'],
    formFields: ['nombre', 'categoriaId', 'tipoId', 'maquinaId', 'linkVideo', 'linkAM'],
    canCreate: true,
    canDelete: true,
  },
  {
    key: 'maquina',
    title: 'Maquinas',
    subtitle: 'Inventario de maquinas',
    path: '/maquinas',
    endpoint: '/maquina',
    idField: 'maquinaId',
    fields: ['maquinaId', 'numeroMaquina', 'nombre', 'linkFoto'],
    formFields: ['nombre', 'numeroMaquina', 'linkFoto'],
    numberFields: ['numeroMaquina'],
    canCreate: true,
    canDelete: true,
  },
  {
    key: 'categoria',
    title: 'Categorias',
    subtitle: 'Clasificacion de ejercicios',
    path: '/categorias',
    endpoint: '/categoria',
    idField: 'categoriaId',
    fields: ['categoriaId', 'nombre'],
    formFields: ['nombre'],
    canCreate: true,
    canDelete: true,
  },
  {
    key: 'tipo',
    title: 'Tipos',
    subtitle: 'Tipos de ejercicios',
    path: '/tipos',
    endpoint: '/tipo',
    idField: 'tipoId',
    fields: ['tipoId', 'nombre'],
    formFields: ['nombre'],
    canCreate: true,
    canDelete: true,
  },
  {
    key: 'plan-entrenamiento',
    title: 'Planes de entrenamiento',
    subtitle: 'Planes de entrenamiento activos',
    path: '/planes',
    endpoint: '/plan-entrenamiento',
    idField: 'planEntrenamientoId',
    fields: ['planEntrenamientoId', 'nombre', 'descripcion', 'duracionDias', 'objetivo', 'usuario.correo'],
    formFields: ['nombre', 'descripcion', 'duracionDias', 'objetivo', 'usuarioId'],
    numberFields: ['duracionDias'],
    canCreate: true,
    canDelete: true,
  },
  {
    key: 'rutina-dia',
    title: 'Rutina dia',
    subtitle: 'Dias de plan de entrenamiento',
    path: '/rutina-dia',
    endpoint: '/rutina-dia',
    idField: 'rutinaDiaId',
    fields: ['rutinaDiaId', 'numeroDia', 'nombre', 'descripcion', 'descansoSegundos', 'finalizada', 'planEntrenamiento.planEntrenamientoId'],
    formFields: ['numeroDia', 'nombre', 'descripcion', 'descansoSegundos', 'planEntrenamientoId'],
    numberFields: ['numeroDia', 'descansoSegundos'],
    canCreate: true,
    canDelete: true,
  },
  {
    key: 'rutina-ejercicio',
    title: 'Rutina ejercicio',
    subtitle: 'Ejercicios por dia de rutina',
    path: '/rutina-ejercicio',
    endpoint: '/rutina-ejercicio',
    idField: 'rutinaEjercicioId',
    fields: ['rutinaEjercicioId', 'orden', 'series', 'repeticiones', 'carga', 'notasEspecificas', 'rutinaDia.rutinaDiaId', 'ejercicio.ejercicioId'],
    formFields: ['orden', 'series', 'repeticiones', 'carga', 'notasEspecificas', 'rutinaDiaId', 'ejercicioId'],
    numberFields: ['orden', 'series', 'repeticiones'],
    canCreate: true,
    canDelete: true,
  },
  {
    key: 'evento',
    title: 'Eventos',
    subtitle: 'Eventos y actividades del gimnasio',
    path: '/eventos',
    endpoint: '/evento',
    idField: 'eventoId',
    fields: ['eventoId', 'nombre', 'fechaHora', 'lugar', 'descripcion'],
    formFields: ['nombre', 'fechaHora', 'lugar', 'descripcion'],
    dateFields: ['fechaHora'],
    canCreate: true,
    canDelete: true,
  },
  {
    key: 'horario',
    title: 'Horario',
    subtitle: 'Horarios de apertura y cierre',
    path: '/horarios',
    endpoint: '/horario',
    idField: 'horarioId',
    fields: ['horarioId', 'diasSemanales', 'apertura', 'cierre'],
    formFields: ['diasSemanales', 'apertura', 'cierre'],
    canCreate: true,
    canDelete: true,
  },
  {
    key: 'sugerencia',
    title: 'Sugerencias',
    subtitle: 'Sugerencias enviadas por usuarios',
    path: '/sugerencias',
    endpoint: '/sugerencia',
    idField: 'sugerenciaId',
    fields: ['tipo', 'actividad', 'contenido', 'solucionada'],
    formFields: [],
    canCreate: false,
    canDelete: false,
  },
];

export const MODULE_MAP = Object.fromEntries(MODULES.map((item) => [item.key, item]));
